[package]
name = "lottery"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
sha2 = "0.10"
solana-client = "2.1"
solana-sdk = "2.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }